apiVersion: v1
kind: Service
metadata:
  name: "{{ printf "sr-%s" .Release.Name }}"
spec:
  type: NodePort
  ports:
  - port: {{.Values.Port}}
    nodePort: {{.Values.NodePort}}
  selector:
    component: "{{ printf "sr-%s-0" .Release.Name }}"
