apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
    name: "{{ printf "eps-%s" .Release.Name | trunc 24 }}"
    annotations:
      helm.sh/created: {{.Release.Time.Seconds | quote }}
    labels:
      heritage: {{.Release.Service | quote }}
      release: {{.Release.Name | quote }}
      chart: "{{.Chart.Name}}-{{.Chart.Version}}"
      component: "{{ printf "eps-%s" .Release.Name  | trunc 24  }}"
spec:
  serviceName: "{{ printf "eps-%s-0" .Release.Name | trunc 24 }}"
  replicas: {{.Values.replicaCount}}
  template:
    metadata:
      labels:
        component: "{{ printf "eps-%s-0" .Release.Name | trunc 24 }}"
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: event-parser
        image: "{{.Values.Image}}:{{ .Values.ImageTag }}"
        env:
        - name: APPLICATION_ID
          value: {{ .Values.application_Id | quote }}
        - name: APPLICATION_HOME
          value: {{ .Values.application_Home | quote }}
        - name: FLOW_DIRECTORY
          value: {{.Values.flow_Directory | quote }}
        - name: INSTRUMENTATION_ON
          value: {{ .Values.instrumentation_On | quote }}
        - name: INSTRUMENTATION_METHOD
          value: {{ .Values.instrumentation_Method | quote }}
        - name: INSTRUMENTATION_FILE_LOCATION
          value: {{ .Values.instrumentation_File_Location | quote }}
        - name: LOGBACK_FILE
          value: {{ .Values.logback_File | quote }}
        - name: LOG_DIR
          value: {{ .Values.log_Dir | quote }}
        - name: MAX_HEAP_SIZE_GB
          value: {{ .Values.heap_Max | quote }}
        - name: INITIAL_HEAP_SIZE_GB
          value: {{ .Values.heap | quote}}
        - name: EVENT_PARSER_CONNECTION_URL
          value: "{{ printf "sr-%s:8081" .Release.Name }}"
        - name: EVENT_PARSER_HOST_NAME
          value: "{{ printf "eps-%s-0.schema.default.svc.cluster.local" .Release.Name | trunc 24 }}"
        - name: EVENT_PARSER_LISTENERS
          value: "{{ printf "http://0.0.0.0:%s" .Values.Port }}"
        - name: schemaRegistry
          value: "{{ printf "sr-%s" .Release.Name }}:{{ printf "%s" .Values.schemaregistry.Port }}"
        ports:
        - containerPort: {{.Values.Port}}
        volumeMounts:
        - name: nfs
          mountPath: /ericsson/apeps/ipl
      volumes:
      - name: nfs
        persistentVolumeClaim:
          claimName: nfs
